# Use the official Python image as the base image
FROM python:3

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY order.py .

# Run the Python script when the container starts
CMD ["python", "order.py"]
